# topic_exploration_task:
#   description: >
#     Define the scope of the presentation topic and create a detailed structure for a 30-slide deck.  
#     Break the topic into 4 major subtopics per slide and assign logical headings and subheadings for each slide.  
#     Ensure the structure covers the topic thoroughly and provides clear focus areas.  
#   expected_output: >
#     A structured outline report with:
#     - 30 slides along with headings and subheadings and slide number.
#     - Subheadings and further breakdowns to cover a topic.
#     - The last slide for references.
#     - A clear, logical sequence for the slides.
#     - No filler sides like hello, thank you, q&a, discussions etc. Just pure raw topic related content.
#   agent: topic_explorer


# detailed_research_task:
#   description: >
#     Conduct comprehensive research on {topic}.  
#     Use the tool provided to gather up-to-date, credible information and cover all critical aspects of the topics and subtopics.  
#     Ensure insights are accurate, actionable, and include supporting statistics and data.  
#     When providing examples or case studies, you ensure all links are working and current. 
#     You check the age and validity of all sources before including them.
#   expected_output: >
#     A detailed 30 slides document based on the outline of 30 slides document created by topic_explorer agent, where each slide incorporates:
#     - Detailed and comprehensive information on each slide based on topics and subtopics.
#     - 2 real-life examples and 2 case studies supporting data as per slide covering key aspects of the subtopics.
#     - Supporting details like statistics, data points, or notable quotes. Ensure every sentence used is accurate, and directly relevant to the topic.
#     - URLs to the sources for validation hyperlinked to the text. The links are not surface level just linking the main website but the exact website page where the information is taken from. 
#     - The links are not surface level (just linking the main website) but the exact website page where the information is taken from.
#     - Does NOT generate any links on it's own, rather uses the tool provided for this.
#   agent: indepth_researcher


# example_finding_task:
#   description: >
#     Identify real-life examples, case studies, or practical applications related to {topic}.  
#     Highlight specific results, challenges, or innovations that demonstrate the topic's and subtopic’s impact.  
#     Ensure examples are relevant to 2024-2025 and come from credible sources.
#   expected_output: >
#     A detailed 30 slides document containing all the information generated by indepth_researcher agent, where each slide incorporates:
#     - 2 real-world examples and 2 case studies for the each subtopic.
#     - Brief descriptions of each example, including their significance.
#     - Source URLs for verification, hyperlinked on the each slide.
#     - No broken links, no links with 404 error or page not found error and whatever is said in the slide can be verified from the source. 
#     - The links are not surface level just linking the main website but the exact website page where the information is taken from.
#     - Does NOT generate any links on it's own, rather uses Serper Google Search Tool provided for this.
#   agent: example_finder


topic_exploration_task:
  description: >
    Define the scope and structure of a 30-slide deck.  
    Break the topic into 4 major subtopics per slide with clear headings and subheadings.  
    Ensure a thorough, structured, and logically sequenced outline.
  expected_output: >
    A structured outline with:
    - 30 slides, each with a title, subheadings, and slide number.
    - A breakdown of topics and subtopics.
    - The last slide dedicated to references.
    - No filler slides (e.g., hello, thank you, Q&A, discussions).
  agent: topic_explorer

detailed_research_task:
  description: >
    Conduct in-depth research on {topic} using the provided tool.  
    Gather up-to-date, credible data, ensuring accuracy and relevance.  
    Validate all sources before inclusion.
  expected_output: >
    A detailed 30-slide document following the topic_explorer outline, with each slide containing:
    - Comprehensive insights based on subtopics.
    - 2 real-world examples and 2 case studies per slide with relevant source links.
    - Supporting statistics, data, or notable quotes.
    - Hyperlinked sources that point to the **exact webpage**, not just the main site.
    - No self-generated links; only tool-validated sources.
  agent: indepth_researcher


